CREATE TABLE USERS
(
    ID integer DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_22B87EFD_F99B_4E53_90CA_623E7DD1208C) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    USERNAME varchar(32) NOT NULL
);
CREATE UNIQUE INDEX USERS_USERNAME_UINDEX ON USERS (USERNAME)
