CREATE TABLE USERS
(
  ID integer AUTO_INCREMENT PRIMARY KEY NOT NULL,
  USERNAME varchar(32) NOT NULL
);

INSERT INTO USERS(USERNAME) VALUES('xzc1');
INSERT INTO USERS(USERNAME) VALUES('xzc2');
INSERT INTO USERS(USERNAME) VALUES('xzc3');

