CREATE TABLE PUBLIC.USERS
(
    ID integer AUTO_INCREMENT PRIMARY KEY NOT NULL,
    USERNAME varchar(32) NOT NULL
);

CREATE TABLE `tt` (
    `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE UNIQUE INDEX USERS_USERNAME_UINDEX ON PUBLIC.USERS (USERNAME);
INSERT INTO PUBLIC.USERS (ID, USERNAME) VALUES (1, 'xzc1');